@api = http://localhost:3000/tasks

GET {{api}}

###

GET {{api}}/1

###

GET {{api}}/count

###

POST {{api}}
Content-Type: application/json

{
    "title": "titulo 3",
    "description": "descripcion 3"
}

###
DELETE {{api}}/6

###
UPDATE {{api}}/1
content-Type: application/json

{
    "title": "titulo UPDATEADO",
    "description": "descripcion updateado"
}